repos:
  - repo: https://github.com/Vimjas/vint
    rev: v0.4a4
    hooks:
      - id: vint
        exclude: ^nvim/autoload/plug\.vim$

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.5.2
    hooks:
      - id: stylua-github
        args: [--check]
